# Generated by Django 5.0.6 on 2024-08-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="register", name="chances", field=models.IntegerField(default=3),
        ),
    ]
